name: tutorial
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  copy_with_extension: ^4.0.2
  flutter:
    sdk: flutter
  flutter_data: ^1.4.6
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.5.0
  path_provider: ^2.0.7

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data

dev_dependencies:
  build_runner: ^2.0.4
  copy_with_extension_gen: ^4.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
